### ISSUE TITLE
How I get/create API key and token?

### ISSUE THREAD

**Issue by ramesh8830** [openach/docker-openach#5]
Hi,

anyone please help me create/get api key and token for openach?

Thanks,
Ramesh

**Comment by sbrendtro** [comment]
Please follow the guide at https://openach.com/books/openach-cli-documentation/openach-cli-documentation.

For example though, using the latest version of openach-docker, which includes a docker-compose CLI shortcut:

Create a User:
```
docker-compose run --rm cli user create --user_login=johndoe --user_password=supersecret --user_email_address=johndoe@email.com --user_first_name=John --user_last_name=Doe
```

Set up an Originator for the User:
```
docker-compose run --rm cli user setup --user_id=_uuid-of-your-user-created-above_ --name="Test Originator" --identification=112358130 --routing_number=101000187 --account_number=1234567890
```

Finally, set up your API key for the given User/Originator_info_id pair:
```
/openach apiuser create --user_id=_uuid-of-your-user-created-above_ --originator_info_id=_uuid-of-originator-info-id-created-above_
```

Note, if you have trouble on the second step, your fedach table probably got cleared out due to a bug in 1.9.2 that we just fixed. Reset the database by removing runtime/db/openach.db and restarting via docker-compose, or copy the contents of fedach from the distributed openach database here: https://github.com/openach/openach/blob/master/protected/data/openach.db.init_save
