### ISSUE TITLE
Plans to replace mcrypt 1.0.1 with openssl?

### ISSUE THREAD

**Issue by keebs** [openach/docker-openach#8]
mcrypt 1.0.1 is almost 4 years old and even 1.0.3 is over a year old. (Openach does not support 1.0.3 as far as I know?) To support 1.0.1, we can only run php 7.3.0 which is missing nearly 2 years of bug fixes and security updates. Is there active development to replace mcrypt with openssl? Without this, I cannot justify using this gateway. I had really high hopes when I found openACH. The further I get into the setup, the more disappointed I get. Any guidance is appreciated. TY

**Comment by sbrendtro** [comment]
I'll spend some time on it this week and see if we can get it upgraded
further. Let me know if there is anything else that you think needs
attention, and I'll see what we can do. In particular, I would love to hear
more details on the disappointments. I appreciate the input.

Thanks,
Steve

**Comment by keebs** [comment]
Steve, I initially tried to install from github which wanted to use php 5. Then I tried the docker image which supported no later than php7.3. Then I tried the virtual machine which is using ubuntu 12.04 which is years past it's end of life. Being a payment gateway storing sensitive information and only supporting software that is years out of date is not an ideal situation.

**Comment by sbrendtro** [comment]
@keebs  The docker image is now updated (see note below). The openach/openach project is now compatible through PHP 7.4. The virtual machine (Ubuntu 12.04) hasn't been maintained for some time.

Resolved in commit 6faca2e

### IMPORTANT UPDATE
The most recent changes have upgraded the base image to Ubuntu 20.04 LTS, and PHP 7.4.  Since PHP dropped support for the mcrypt extension in 7.2, we had been installing it from PEAR. To make for a cleaner install, we have moved to use the `phpseclib/mcrypt_compat` package. To accomplish this, there are some significant changes to this project's `Dockerfile`:

1. Removed the PEAR install of mcrypt extension
2. Removed the outdated version of phpseclib from `protected/vendors/phpseclib`
3. Removed old Yii 1.x framework install (previously done via tarball)
4. Added `composer`
5. Added RUN for `composer install` during build

Also to facilitate these changes, changes were made in the `openach/openach` repo:
1. Added a composer.json file to facilitate composer-based library installation
2. Through composer, required `yiisoft/yii`, `phpseclib/phpseclib`, and `phpseclib/mcrypt_compat`, and `cweagans/composer-patches` packages
3. Added a composer patch in `openach/openach` in the `patches` folder, which changes how CSecurityManager in Yii 1.x looks for the mcrypt extension, making it compatible with `phpseclib/mcrypt_compat`
4. Modified the CLI script, along with all PHP entrypoint scripts, to use the composer autoloader, removing references to tarball-based Yii install.

The result for users of this docker container is a new, fully up-to-date platform running on PHP 7.4 that is backwards-compatible with config and data files (including encrypted data) from older installs.

NOTE: If you previously made local customization to `Dockerfile`, you will want to merge those changes very carefully, and ensure that you pull the latest version of code from `openach/openach` that has been updated for PHP 7.4.

### Security Note
PHP 7.2 EOL (end-of-life) was November 30, 2020. __OpenACH is now certified for PHP 7.4. We strongly recommend upgrading to the latest version of this repository.__ 

If you are using a self-built image, please merge any new changes from our distributed Dockerfile into yours and rebuild. 

If you are using our pre-built images, *first back up your data*, then run `docker-compose pull`, and then `docker-compose up -d`.

See https://hub.docker.com/repository/docker/openach/openach/ for the latest build information.
